### ISSUE TITLE
No Output for either image or Video test 

### ISSUE THREAD

**Issue by sguin1** [CMU-Perceptual-Computing-Lab/caffe_rtpose#7]
We compiled and executed the rtpose.bin (w/o making any changes) and for some reason, its not generating any output for either image or video file. 

There is no error either.
I have pasted the command and output below

Any idea why it is not generating json file?

Thanks
================================================
./build/examples/rtpose/rtpose.bin --image_dir /home/xxx/images/dnn/ --write_json output
init done 
opengl support available 
E0109 19:00:27.296622 118173 rtpose.cpp:1538] rtcpm successfully finished.
E0109 19:00:27.296898 118173 rtpose.cpp:1541] Total time: 4.61036 seconds.
xxx@yyy:~/project/dnn/caffe_rtpose$ ls output/

**Comment by sjobeek** [comment]
I've experienced this same issue on an Ubuntu 16.04 machine using OpenCV 3.1 (GTX 1060). 

Any ideas for approaches to debug the issue?

**Comment by ZheC** [comment]
This problem is mainly caused by openCV version difference as reported in https://github.com/CMU-Perceptual-Computing-Lab/caffe_rtpose/issues/2 and https://github.com/CMU-Perceptual-Computing-Lab/caffe_rtpose/issues/5. We made a commit in https://github.com/CMU-Perceptual-Computing-Lab/caffe_rtpose/commit/e1388f76e4f43c54e53b17907d1d8d119277893a Did you use the updated version? One way to debug the issue is to turn off the display and write out the result, e.g., ./build/examples/rtpose/rtpose.bin --video test.mp4 --no_display --write_frames output/ Please let us know if you meet the same problem

**Comment by sjobeek** [comment]
I ended up getting it working with opencv 2.4, but I may try again with 3.1 in the future. 

Thanks for the suggestions.

**Comment by huzhenzhen** [comment]
I met the same problem with opencv 2.4.8. I have tried with --no_display but there is still no output files...

**Comment by gineshidalgo99** [comment]
Solution on #21.
